config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'lists#index'

  resources :lists, except: %i[edit update] do
    resources :bookmarks, only: %i[new create]
  end
  resources :bookmarks, only: :destroy
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list
  validates :comment, length: { minimum: 6 }
  validates_uniqueness_of :movie_id, scope: :list_id
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks
  has_many :movies, through: :bookmarks, dependent: :destroy
  validates :name, uniqueness: true, presence: true
  has_one_attached :photo
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks
  validates :title, presence: true, uniqueness: true
  validates :overview, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  def new
    @list = List.find(params[:list_id])
    @bookmark = Bookmark.new
  end

  def create
    # raise
    @list = List.find(params[:list_id])
    @bookmark = Bookmark.new(bookmark_params)
    @bookmark.list = @list
    if @bookmark.save
      redirect_to list_path(@list)
    else
      render :new
    end
  end

  def destroy
    # raise
    @bookmark = Bookmark.find(params[:id])
    @list = @bookmark.list
    @bookmark.destroy
    redirect_to list_path(@list)
  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:movie_id, :comment)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    @lists = List.all
  end

  def show
    @list = List.find(params[:id])
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to root_path
    else
      render :new
    end
  end

  private

  def list_params
    params.require(:list).permit(:name, :photo)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/bookmarks/new.html.erb
<%= simple_form_for [@list, @bookmark] do |f| %>
  <%= f.input :comment %>
  <%= f.association :movie %>
  <%= f.submit class: 'btn btn-flat' %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

  </head>

  <body>
    <div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
      <a class="navbar-brand" href="#">
        <img src="https://lh3.googleusercontent.com/proxy/94h7KSvRTzv4wUTO-cMBk55NzG_voDcWUQrZxKDmTJZtVnfh6l3NNzBRzE_FXxI0Lipi-8IaqP-9qBXacjxc4eUYlFdbQizX8YxHk7B5L3QH0lB-be7R_G8yvEDvNi5AsddF57guC0f6" />
    </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item">
            <p class="nav-link mb-0"><%= link_to 'my lists', lists_path %></p>
          </li>
          <li class="nav-item">
            <p class="nav-link mb-0"><%= link_to 'new list', new_list_path %></p>
          </li>
        </ul>
      </div>
    </div>

    <%= yield %>
  </body>
</html>

app/views/lists/index.html.erb
<div class="banner text-center" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url('https://images.unsplash.com/photo-1440404653325-ab127d49abc1?ixid=MnwxMjA3fDB8MHxzZWFyY2h8Mnx8ZmlsbXxlbnwwfHwwfHw%3D&ixlib=rb-1.2.1&w=1000&q=80');">
  <div class="container">
    <h1>welcome to the jungle</h1>
  </div>
</div>

<div class="container d-flex">

  <% @lists.each do |list| %>
    <div class="card-category col-3" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= cl_image_path list.photo.key, crop: :fill %>)">
      <p><%= link_to list.name, list_path(list) %></p>
    </div>
  <% end %>

</div>

app/views/lists/new.html.erb
<%= simple_form_for(@list) do |f| %>
  <%= f.input :name %>
  <%= f.input :photo, as: :file %>
  <%= f.button :submit %>
<% end %>

app/views/lists/show.html.erb
<!-- <div class="navbar" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= cl_image_path @list.photo.key, height: 300, crop: :fill %>')">

</div> -->

<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url('<%= cl_image_path @list.photo.key, crop: :fill %>');">
  <div class="container">
    <h1><%= @list.name %></h1>
  </div>
</div>

<div class="container">
  <p class="btn mt-2"><%= link_to 'add a movie', new_list_bookmark_path(@list) %></p>
</div>

<div class="container d-flex">
  <% @list.bookmarks.each do |bookmark| %>
    <div class="card-trip col-4">
      <img src="<%= bookmark.movie.poster_url %>" />
      <div class="card-trip-infos">
        <div>
          <h2><%= bookmark.movie.title %></h2>
          <p><%= bookmark.movie.overview %></p>
        </div>
      </div>
      <div class="card-trip-infos">
        <p><%= bookmark.comment %></p>
        <p class="delete">
        <%= link_to 'x',
        bookmark_path(bookmark),
        method: :delete,
        data: { confirm: "Are you sure?" } %>
        </p>
      </div>
    </div>
  <% end %>
</div>